---
title: "DDS Analytics"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Add libraries
library(rsample)
library(yardstick)
library(corrr)
library(readxl)
library(tidyverse)
library(glmnet)
library(rpart)
library(rpart.plot)
library(randomForest)
```

```{r}
# Load raw data
raw_DDSA <- read_excel("CaseStudy2-data.xlsx")
```

```{r}
# Change characters to factors for more meaningful analysis
DDSA <- raw_DDSA%>%
  mutate_if(is.character, as.factor) %>%
  select(Attrition, everything())

# attach so we don't have to keep writing DDSA$
attach(DDSA)
```

```{r}
# View summary statistics
summary(DDSA)
```


```{r}
# Changed the following variables to categorical to eventually have a LifeSatisfaction variable
DDSA$DistanceFromHome <- cut(DDSA$DistanceFromHome, breaks = c(-Inf, 9, 21, Inf), labels=c("Poor", "Fair", "Good"))

DDSA$RelationshipSatisfaction <- cut(DDSA$RelationshipSatisfaction, breaks = c(-Inf, 2, 3, Inf), labels=c("Poor", "Fair", "Good"))

DDSA$WorkLifeBalance <- cut(DDSA$WorkLifeBalance, breaks = c(-Inf, 2, 3, Inf), labels=c("Poor", "Fair", "Good"))
```


```{r}
# Chart depicting Gender vs attrition
ggplot(DDSA, aes(Gender, ..count.., fill = factor(Attrition))) + 
  geom_bar(position="dodge") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle('Attrition Based on Gender') +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
# Chart depicting Monthly Income vs attrition
qplot(DDSA$MonthlyIncome,
      geom="histogram",binwidth = 500, main = "Histogram for Monthly Income",
      xlab = "Monthly Income",
      fill=I("light blue"),
      col=I("orange"))

```

```{r}
# Chart depicting Age vs attrition
qplot(DDSA$Age,
      geom="histogram",binwidth = 5, main = "Histogram for Age",
      xlab = "Age",
      fill=I("light blue"),
      col=I("orange"))
```


```{r}
# Chart depicting Years at Company vs attrition
qplot(DDSA$YearsAtCompany,
      geom="histogram",binwidth = 2, main = "Histogram for Years at the company",
      xlab = "Years at company",
      fill=I("light blue"),
      col=I("orange"))

```


```{r}
# Is there a relationship between Age and Income. 
# Color each point based on the Gender of the participant
ggplot(data=DDSA) +
  geom_point(mapping = aes(x = Age, y = MonthlyIncome, color=Gender)) +
  geom_smooth(mapping = aes(x = Age, y = MonthlyIncome)) + 
  xlab('Age') + ylab('Income') +
  ggtitle('Age vs Income') +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r}
# Split test/training sets ~ uses the rsample package
set.seed(100)
train_test_split <- initial_split(DDSA, prop = 0.8)
train_test_split

# Retrieve train and test sets
train_tbl <- training(train_test_split)
test_tbl <- testing(train_test_split)
```

```{r}
# Breakdown of the test split ~ using 80% to test
table(test_tbl$Attrition)
237/nrow(test_tbl)
```

```{r}
# Grow our classification trees
modelCart = rpart(Attrition ~ ., data=train_tbl, method="class")
#Plot the model
prp(modelCart)

```


```{r}
#Predict the test data
predictionCart <- predict(modelCart, newdata=test_tbl, type="class")
#CART Accuracy
#Confusion matrix 
t1 <- table(test_tbl$Attrition, predictionCart)
print(t1)
```


```{r}
#CART model accuracy
(t1[1]+t1[4])/(nrow(test_tbl))
```


```{r}
# Random Forest model
modelRf = randomForest(Attrition ~ ., data=train_tbl, ntree = 100, mtry = 5, importance = TRUE, method="class")
print(modelRf)
```


